name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    permissions: read-all
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'nsideris'
        reponame: 'Devoxx2023UI'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
